export default [
  {
    documentNumber: 20628,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Fiji",
    customer: "Merry",
    service: "Voice",
    bank: "ZABA",
    documentDate: "11.09.2018",
    ammount: 1897.09,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 89708,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Qatar",
    customer: "Eolanda",
    service: "Voice",
    bank: "ZABA",
    documentDate: "09.24.2014",
    ammount: 4194.71,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 10617,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Jamaica",
    customer: "Andeee",
    service: "Viber",
    bank: "Raiffeisen",
    documentDate: "05.14.2016",
    ammount: 5774.14,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 27718,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Comoros",
    customer: "Louella",
    service: "Voice",
    bank: "HPB",
    documentDate: "07.14.2018",
    ammount: 4110.93,
    currency: "USD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 45530,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Equatorial Guinea",
    customer: "Loree",
    service: "Viber",
    bank: "OTP",
    documentDate: "12.06.2018",
    ammount: 2562.76,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 35129,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Hungary",
    customer: "Brietta",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "04.28.2016",
    ammount: 8163.84,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 76209,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Maldives",
    customer: "Eadie",
    service: "Other",
    bank: "Barclays",
    documentDate: "07.24.2014",
    ammount: 9003.16,
    currency: "CAD",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 18301,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Qatar",
    customer: "Jan",
    service: "Viber",
    bank: "PBZ",
    documentDate: "02.20.2017",
    ammount: 4517.75,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 52358,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Sao Tome and Principe",
    customer: "Aili",
    service: "Voice",
    bank: "OTP",
    documentDate: "04.14.2016",
    ammount: 9699.07,
    currency: "CAD",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 43760,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Equatorial Guinea",
    customer: "Gaylene",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "07.29.2011",
    ammount: 1101.3,
    currency: "GBP",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 76920,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2015,
    company: "AndorrA",
    customer: "Agathe",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "11.20.2012",
    ammount: 1452.44,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 99087,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Turkey",
    customer: "Luci",
    service: "SMS",
    bank: "PBZ",
    documentDate: "06.26.2011",
    ammount: 1385.05,
    currency: "USD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 42455,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Guyana",
    customer: "Allyce",
    service: "Voice",
    bank: "ZABA",
    documentDate: "02.06.2018",
    ammount: 9622.84,
    currency: "USD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 32240,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Saint Lucia",
    customer: "Joy",
    service: "Viber",
    bank: "ZABA",
    documentDate: "04.19.2018",
    ammount: 5836.57,
    currency: "AUD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 81213,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Nauru",
    customer: "Tatiania",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "11.17.2015",
    ammount: 6625.53,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 94459,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Guinea",
    customer: "Shaylyn",
    service: "Other",
    bank: "HPB",
    documentDate: "07.15.2016",
    ammount: 6200.44,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 85683,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Argentina",
    customer: "Christian",
    service: "Viber",
    bank: "PBZ",
    documentDate: "03.12.2018",
    ammount: 150.76,
    currency: "SEK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 48584,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Tunisia",
    customer: "Bobinette",
    service: "SMS",
    bank: "ZABA",
    documentDate: "11.10.2011",
    ammount: 2020.97,
    currency: "AUD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 31378,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "Åland Islands",
    customer: "Merrie",
    service: "Voice",
    bank: "ZABA",
    documentDate: "03.16.2011",
    ammount: 6832.94,
    currency: "EUR",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 77248,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "RWANDA",
    customer: "Ruthe",
    service: "Viber",
    bank: "Erste",
    documentDate: "08.20.2011",
    ammount: 6201.01,
    currency: "GBP",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 58023,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Saint Kitts and Nevis",
    customer: "Rhea",
    service: "Viber",
    bank: "HPB",
    documentDate: "05.03.2010",
    ammount: 4806.57,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 55986,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Northern Mariana Islands",
    customer: "Jaime",
    service: "Other",
    bank: "HPB",
    documentDate: "09.26.2013",
    ammount: 7170.04,
    currency: "USD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 75845,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Gabon",
    customer: "Nyssa",
    service: "Viber",
    bank: "ZABA",
    documentDate: "10.01.2016",
    ammount: 4946.29,
    currency: "GBP",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 50169,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Bosnia and Herzegovina",
    customer: "Brooks",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "06.19.2016",
    ammount: 2535.43,
    currency: "USD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 87110,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Iraq",
    customer: "Orsola",
    service: "SMS",
    bank: "Erste",
    documentDate: "02.09.2018",
    ammount: 7746.87,
    currency: "USD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 31521,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Burkina Faso",
    customer: "Dacia",
    service: "Voice",
    bank: "Hypo",
    documentDate: "10.18.2010",
    ammount: 1739.83,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 10676,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "Suriname",
    customer: "Ronna",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "11.03.2017",
    ammount: 6975.06,
    currency: "AUD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 38777,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Guadeloupe",
    customer: "Jordan",
    service: "Voice",
    bank: "PBZ",
    documentDate: "07.06.2012",
    ammount: 6414.3,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 99574,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Germany",
    customer: "Annabela",
    service: "Voice",
    bank: "HPB",
    documentDate: "03.19.2018",
    ammount: 2656.33,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 47767,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Mauritius",
    customer: "Etta",
    service: "WhatsApp",
    bank: "Barclays",
    documentDate: "06.22.2011",
    ammount: 2785.77,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 77659,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Botswana",
    customer: "Kaia",
    service: "Viber",
    bank: "Hypo",
    documentDate: "12.08.2014",
    ammount: 6608.12,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 41249,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Cayman Islands",
    customer: "Helena",
    service: "Other",
    bank: "Erste",
    documentDate: "01.18.2017",
    ammount: 7055.18,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 71958,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Puerto Rico",
    customer: "Adele",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "03.31.2015",
    ammount: 5676.37,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 80316,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Slovakia",
    customer: "Thalia",
    service: "WhatsApp",
    bank: "Raiffeisen",
    documentDate: "11.22.2014",
    ammount: 2544.35,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 82872,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "American Samoa",
    customer: "Emmey",
    service: "Viber",
    bank: "Barclays",
    documentDate: "06.26.2011",
    ammount: 7428.7,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 41257,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Benin",
    customer: "Cherrita",
    service: "SMS",
    bank: "Hypo",
    documentDate: "08.17.2014",
    ammount: 2458.62,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 45634,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Qatar",
    customer: "Vevay",
    service: "Voice",
    bank: "PBZ",
    documentDate: "01.12.2015",
    ammount: 9606.65,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 38035,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Netherlands",
    customer: "Allis",
    service: "Other",
    bank: "Revolut",
    documentDate: "08.28.2010",
    ammount: 3868.84,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 37453,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Sudan",
    customer: "Chastity",
    service: "Voice",
    bank: "OTP",
    documentDate: "10.09.2018",
    ammount: 2928.26,
    currency: "SEK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 20871,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "Montserrat",
    customer: "Dennie",
    service: "SMS",
    bank: "ZABA",
    documentDate: "01.29.2012",
    ammount: 7580.83,
    currency: "USD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 21524,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Brunei Darussalam",
    customer: "Brandise",
    service: "Viber",
    bank: "Erste",
    documentDate: "11.17.2017",
    ammount: 6580.77,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 60061,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Mexico",
    customer: "Isa",
    service: "SMS",
    bank: "HPB",
    documentDate: "08.26.2014",
    ammount: 7551.68,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 37911,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Greenland",
    customer: "Britte",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "08.17.2012",
    ammount: 3857.61,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 54094,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Åland Islands",
    customer: "Gusty",
    service: "WhatsApp",
    bank: "Barclays",
    documentDate: "11.27.2016",
    ammount: 3503.04,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 50469,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Montserrat",
    customer: "Yolane",
    service: "Voice",
    bank: "ZABA",
    documentDate: "07.14.2012",
    ammount: 5773.06,
    currency: "USD",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 61032,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Switzerland",
    customer: "Merle",
    service: "Viber",
    bank: "PBZ",
    documentDate: "11.02.2014",
    ammount: 9664.68,
    currency: "CAD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 62570,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Malaysia",
    customer: "Madalyn",
    service: "SMS",
    bank: "Revolut",
    documentDate: "07.23.2016",
    ammount: 3575.69,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 57899,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Saint Pierre and Miquelon",
    customer: "Sibella",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "08.20.2014",
    ammount: 3301.66,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 80285,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2013,
    company: "Bolivia",
    customer: "Harmonia",
    service: "Other",
    bank: "HPB",
    documentDate: "05.01.2018",
    ammount: 5499.71,
    currency: "CAD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 85443,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Cuba",
    customer: "Taffy",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "05.13.2014",
    ammount: 4861.54,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 86055,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Liechtenstein",
    customer: "Priscilla",
    service: "Other",
    bank: "Erste",
    documentDate: "05.29.2015",
    ammount: 8616.47,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 77824,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Portugal",
    customer: "Kittie",
    service: "Other",
    bank: "Erste",
    documentDate: "06.06.2016",
    ammount: 9307.22,
    currency: "USD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 88394,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Eritrea",
    customer: "Nickie",
    service: "Other",
    bank: "PBZ",
    documentDate: "04.03.2012",
    ammount: 3866.55,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 68369,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Pitcairn",
    customer: "Stevana",
    service: "Viber",
    bank: "Hypo",
    documentDate: "08.16.2010",
    ammount: 1026.87,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 92022,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Tokelau",
    customer: "Raf",
    service: "Other",
    bank: "Barclays",
    documentDate: "03.22.2011",
    ammount: 2410.88,
    currency: "AUD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 57148,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Canada",
    customer: "Harrietta",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "06.09.2010",
    ammount: 4217.36,
    currency: "AUD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 45609,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "New Caledonia",
    customer: "Harmonia",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "11.25.2017",
    ammount: 7600.08,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 71144,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Reunion",
    customer: "Margarette",
    service: "Other",
    bank: "ZABA",
    documentDate: "04.29.2018",
    ammount: 7157.78,
    currency: "CAD",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 92091,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Kuwait",
    customer: "Kaja",
    service: "SMS",
    bank: "Barclays",
    documentDate: "10.25.2015",
    ammount: 5346.12,
    currency: "AUD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 14724,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2013,
    company: "Brunei Darussalam",
    customer: "Phedra",
    service: "SMS",
    bank: "Barclays",
    documentDate: "01.23.2015",
    ammount: 9283.12,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 78622,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Chad",
    customer: "Deirdre",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "08.02.2012",
    ammount: 3711.25,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 20845,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Latvia",
    customer: "Starla",
    service: "Voice",
    bank: "HPB",
    documentDate: "02.19.2013",
    ammount: 4555.45,
    currency: "USD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 75524,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Saint Kitts and Nevis",
    customer: "Carree",
    service: "Voice",
    bank: "Erste",
    documentDate: "02.11.2011",
    ammount: 5203.34,
    currency: "EUR",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 40761,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Isle of Man",
    customer: "Arlena",
    service: "Voice",
    bank: "Hypo",
    documentDate: "04.07.2018",
    ammount: 452.7,
    currency: "EUR",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 27210,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Sudan",
    customer: "Caritta",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "03.22.2018",
    ammount: 6856.95,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 47712,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Zambia",
    customer: "Therine",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "10.27.2014",
    ammount: 9044.88,
    currency: "SEK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 26555,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Syrian Arab Republic",
    customer: "Karina",
    service: "Other",
    bank: "Hypo",
    documentDate: "01.05.2013",
    ammount: 7201.39,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 75507,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Poland",
    customer: "Kimberley",
    service: "SMS",
    bank: "Hypo",
    documentDate: "05.04.2017",
    ammount: 7344.42,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 77491,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Seychelles",
    customer: "Marleah",
    service: "Other",
    bank: "Hypo",
    documentDate: "06.09.2010",
    ammount: 8686.82,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 19791,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "French Guiana",
    customer: "Vivia",
    service: "Viber",
    bank: "Hypo",
    documentDate: "01.13.2017",
    ammount: 7327.73,
    currency: "SEK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 65806,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Romania",
    customer: "Janey",
    service: "Voice",
    bank: "OTP",
    documentDate: "12.03.2011",
    ammount: 5081.92,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 63906,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "New Caledonia",
    customer: "Yvonne",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "06.11.2017",
    ammount: 7826.93,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 17004,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2015,
    company: "Sri Lanka",
    customer: "Kayla",
    service: "Voice",
    bank: "Revolut",
    documentDate: "07.23.2012",
    ammount: 7709.83,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 44302,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Bermuda",
    customer: "Marti",
    service: "Viber",
    bank: "HPB",
    documentDate: "10.01.2017",
    ammount: 431.06,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 35678,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Nigeria",
    customer: "Emelina",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "01.18.2016",
    ammount: 3472.02,
    currency: "USD",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 80385,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2015,
    company: "Poland",
    customer: "Theodora",
    service: "Viber",
    bank: "Barclays",
    documentDate: "07.04.2014",
    ammount: 2543.1,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 60705,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2017,
    company: "Ireland",
    customer: "Orsola",
    service: "Viber",
    bank: "OTP",
    documentDate: "07.26.2016",
    ammount: 3723.57,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 43073,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2015,
    company: "Reunion",
    customer: "Sallie",
    service: "SMS",
    bank: "Revolut",
    documentDate: "05.17.2015",
    ammount: 1925.82,
    currency: "USD",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 43738,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Solomon Islands",
    customer: "Fidelia",
    service: "WhatsApp",
    bank: "Barclays",
    documentDate: "10.05.2011",
    ammount: 8660.44,
    currency: "GBP",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 63999,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "American Samoa",
    customer: "Wileen",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "05.21.2011",
    ammount: 4697.82,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 81472,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Yemen",
    customer: "Ada",
    service: "Viber",
    bank: "Hypo",
    documentDate: "11.15.2014",
    ammount: 1279.24,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 59898,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: 'Korea, Democratic People"S Republic of',
    customer: "Hollie",
    service: "SMS",
    bank: "Raiffeisen",
    documentDate: "11.02.2015",
    ammount: 1129.27,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 18510,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Jordan",
    customer: "Sallie",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "08.23.2013",
    ammount: 4497.08,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 55066,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Dominican Republic",
    customer: "Kaia",
    service: "SMS",
    bank: "Raiffeisen",
    documentDate: "06.20.2014",
    ammount: 6237.76,
    currency: "GBP",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 49383,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Timor-Leste",
    customer: "Merle",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "12.24.2018",
    ammount: 4657.92,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 31639,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Central African Republic",
    customer: "Gilligan",
    service: "Other",
    bank: "Erste",
    documentDate: "12.01.2017",
    ammount: 1166.19,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 13896,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Germany",
    customer: "Asia",
    service: "SMS",
    bank: "Erste",
    documentDate: "08.10.2014",
    ammount: 5168.73,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 11780,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Åland Islands",
    customer: "Farrah",
    service: "Voice",
    bank: "Erste",
    documentDate: "07.30.2014",
    ammount: 4566.01,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 42258,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Virgin Islands, British",
    customer: "Iseabal",
    service: "Voice",
    bank: "Barclays",
    documentDate: "11.12.2018",
    ammount: 2384.1,
    currency: "USD",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 93531,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Solomon Islands",
    customer: "Melodie",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "02.23.2011",
    ammount: 3557.7,
    currency: "HRK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 89687,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Zimbabwe",
    customer: "Lesly",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "01.20.2016",
    ammount: 5401.62,
    currency: "SEK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 61168,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Kyrgyzstan",
    customer: "Adore",
    service: "Other",
    bank: "OTP",
    documentDate: "10.09.2012",
    ammount: 5643.56,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 18709,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2017,
    company: "Wallis and Futuna",
    customer: "Gale",
    service: "Voice",
    bank: "Revolut",
    documentDate: "11.19.2015",
    ammount: 4991.78,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 68086,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Gibraltar",
    customer: "Nickie",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "06.05.2011",
    ammount: 6119.43,
    currency: "SEK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 71101,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Venezuela",
    customer: "Debee",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "04.09.2011",
    ammount: 4300.74,
    currency: "EUR",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 18012,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Tuvalu",
    customer: "Fernande",
    service: "Other",
    bank: "PBZ",
    documentDate: "04.12.2013",
    ammount: 7761.75,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 43227,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Tanzania, United Republic of",
    customer: "Winifred",
    service: "WhatsApp",
    bank: "Barclays",
    documentDate: "10.20.2012",
    ammount: 364,
    currency: "GBP",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 81469,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Switzerland",
    customer: "Elmira",
    service: "Voice",
    bank: "OTP",
    documentDate: "10.21.2015",
    ammount: 6984.03,
    currency: "EUR",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 81575,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "China",
    customer: "Angela",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "04.19.2013",
    ammount: 9858.41,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 81731,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Nauru",
    customer: "Edee",
    service: "SMS",
    bank: "Hypo",
    documentDate: "07.03.2018",
    ammount: 2726.34,
    currency: "EUR",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 33853,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Falkland Islands (Malvinas)",
    customer: "Lynea",
    service: "Other",
    bank: "OTP",
    documentDate: "07.16.2012",
    ammount: 1827.23,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 72991,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Guatemala",
    customer: "Annecorinne",
    service: "Viber",
    bank: "Hypo",
    documentDate: "05.09.2012",
    ammount: 1439.83,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 54748,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Kazakhstan",
    customer: "Therine",
    service: "Other",
    bank: "ZABA",
    documentDate: "10.06.2018",
    ammount: 2372.38,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 71086,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Guadeloupe",
    customer: "Frank",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "07.12.2011",
    ammount: 2582.54,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 67367,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Algeria",
    customer: "Nikki",
    service: "SMS",
    bank: "PBZ",
    documentDate: "04.07.2010",
    ammount: 225.43,
    currency: "CAD",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 83268,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Greenland",
    customer: "Clarice",
    service: "Voice",
    bank: "PBZ",
    documentDate: "06.01.2014",
    ammount: 1298.04,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 51350,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Chad",
    customer: "Claudina",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "09.12.2013",
    ammount: 4819.9,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 75467,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Hong Kong",
    customer: "Mellicent",
    service: "Viber",
    bank: "Revolut",
    documentDate: "06.29.2014",
    ammount: 4048.84,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 48465,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "El Salvador",
    customer: "Yvonne",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "10.07.2014",
    ammount: 3436.56,
    currency: "SEK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 26767,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Lesotho",
    customer: "Allis",
    service: "SMS",
    bank: "Hypo",
    documentDate: "08.29.2014",
    ammount: 8734.51,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 72816,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Lebanon",
    customer: "Jacquetta",
    service: "SMS",
    bank: "PBZ",
    documentDate: "08.02.2016",
    ammount: 8816.74,
    currency: "USD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 45152,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Faroe Islands",
    customer: "Claudina",
    service: "Other",
    bank: "ZABA",
    documentDate: "06.02.2011",
    ammount: 5130.73,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 47005,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Turks and Caicos Islands",
    customer: "Ileana",
    service: "WhatsApp",
    bank: "Raiffeisen",
    documentDate: "09.14.2011",
    ammount: 5676.99,
    currency: "SEK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 98933,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Costa Rica",
    customer: "Amalie",
    service: "Voice",
    bank: "Hypo",
    documentDate: "05.03.2014",
    ammount: 5716.25,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 40893,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Libyan Arab Jamahiriya",
    customer: "Katharina",
    service: "Viber",
    bank: "ZABA",
    documentDate: "01.01.2019",
    ammount: 3676.02,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 33921,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Malta",
    customer: "Verla",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "02.11.2012",
    ammount: 8871.93,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 31554,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Virgin Islands, U.S.",
    customer: "Clo",
    service: "Other",
    bank: "Hypo",
    documentDate: "03.13.2017",
    ammount: 6595.69,
    currency: "USD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 39623,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Pitcairn",
    customer: "Halette",
    service: "Viber",
    bank: "Revolut",
    documentDate: "12.29.2018",
    ammount: 8971.78,
    currency: "SEK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 75389,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Bolivia",
    customer: "Cordi",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "06.14.2012",
    ammount: 2613.16,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 20957,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Greenland",
    customer: "Arlena",
    service: "Other",
    bank: "Revolut",
    documentDate: "09.01.2013",
    ammount: 2841.99,
    currency: "GBP",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 77790,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Peru",
    customer: "Minda",
    service: "SMS",
    bank: "Hypo",
    documentDate: "04.18.2010",
    ammount: 3489.18,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 11877,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Costa Rica",
    customer: "Tilly",
    service: "Other",
    bank: "Barclays",
    documentDate: "12.19.2013",
    ammount: 5737.06,
    currency: "HRK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 80860,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Ethiopia",
    customer: "Brana",
    service: "Viber",
    bank: "HPB",
    documentDate: "06.09.2016",
    ammount: 4205.57,
    currency: "USD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 27955,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Kiribati",
    customer: "Marinna",
    service: "Other",
    bank: "Hypo",
    documentDate: "03.08.2016",
    ammount: 9942.76,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 95464,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Saint Lucia",
    customer: "Giustina",
    service: "Viber",
    bank: "OTP",
    documentDate: "12.13.2017",
    ammount: 8576.34,
    currency: "USD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 80941,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2012,
    company: "Saint Pierre and Miquelon",
    customer: "Benita",
    service: "Voice",
    bank: "HPB",
    documentDate: "10.23.2015",
    ammount: 1219.81,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 49617,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "United States Minor Outlying Islands",
    customer: "Atlanta",
    service: "SMS",
    bank: "Barclays",
    documentDate: "09.12.2014",
    ammount: 9743.8,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 60843,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Albania",
    customer: "Layla",
    service: "SMS",
    bank: "HPB",
    documentDate: "01.16.2011",
    ammount: 7954.07,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 76945,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Somalia",
    customer: "Carolina",
    service: "Viber",
    bank: "Revolut",
    documentDate: "06.03.2013",
    ammount: 9648,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 63577,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Zambia",
    customer: "Rebeca",
    service: "Voice",
    bank: "Erste",
    documentDate: "09.24.2010",
    ammount: 9821.64,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 15235,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Austria",
    customer: "Wendi",
    service: "Viber",
    bank: "HPB",
    documentDate: "05.05.2012",
    ammount: 6741.12,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 64755,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Hong Kong",
    customer: "Wanda",
    service: "Other",
    bank: "HPB",
    documentDate: "06.09.2018",
    ammount: 3586.55,
    currency: "GBP",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 83248,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Jersey",
    customer: "Melodie",
    service: "SMS",
    bank: "OTP",
    documentDate: "03.13.2010",
    ammount: 7536.06,
    currency: "SEK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 63286,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Morocco",
    customer: "Carol-Jean",
    service: "Other",
    bank: "ZABA",
    documentDate: "05.15.2011",
    ammount: 6450.95,
    currency: "GBP",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 85159,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Sudan",
    customer: "Elfreda",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "03.29.2018",
    ammount: 904.17,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 99277,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Congo",
    customer: "Sara-Ann",
    service: "Voice",
    bank: "Erste",
    documentDate: "01.07.2014",
    ammount: 3563.78,
    currency: "CAD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 16283,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Jersey",
    customer: "Kimberley",
    service: "SMS",
    bank: "OTP",
    documentDate: "04.27.2017",
    ammount: 2908.07,
    currency: "SEK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 76018,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Cocos (Keeling) Islands",
    customer: "Margette",
    service: "Other",
    bank: "Barclays",
    documentDate: "01.25.2015",
    ammount: 1021.97,
    currency: "EUR",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 19643,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Palestinian Territory, Occupied",
    customer: "Ardenia",
    service: "Voice",
    bank: "PBZ",
    documentDate: "11.23.2014",
    ammount: 7724.21,
    currency: "GBP",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 89639,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Belize",
    customer: "Adriana",
    service: "SMS",
    bank: "Revolut",
    documentDate: "10.23.2013",
    ammount: 4981.47,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 94364,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "Reunion",
    customer: "Kara-Lynn",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "10.21.2017",
    ammount: 2802.63,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 42474,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Georgia",
    customer: "Pearline",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "03.09.2010",
    ammount: 7490.49,
    currency: "USD",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 76751,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2015,
    company: "Virgin Islands, British",
    customer: "Sean",
    service: "Viber",
    bank: "ZABA",
    documentDate: "04.26.2015",
    ammount: 4030.19,
    currency: "AUD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 31044,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Gibraltar",
    customer: "Mariele",
    service: "SMS",
    bank: "Revolut",
    documentDate: "03.12.2013",
    ammount: 8253.51,
    currency: "GBP",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 94623,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2010,
    company: "Gambia",
    customer: "Agathe",
    service: "Voice",
    bank: "OTP",
    documentDate: "10.25.2010",
    ammount: 5488.83,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 15841,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "United Arab Emirates",
    customer: "Dode",
    service: "Voice",
    bank: "Erste",
    documentDate: "09.20.2013",
    ammount: 4253.17,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 13713,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Eritrea",
    customer: "Claudina",
    service: "Viber",
    bank: "HPB",
    documentDate: "10.14.2016",
    ammount: 882.75,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 94472,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Egypt",
    customer: "Tobe",
    service: "Other",
    bank: "Barclays",
    documentDate: "03.18.2016",
    ammount: 8503.71,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 13917,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Togo",
    customer: "Tobe",
    service: "SMS",
    bank: "OTP",
    documentDate: "08.14.2014",
    ammount: 4443.77,
    currency: "AUD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 54663,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Dominican Republic",
    customer: "Therine",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "11.23.2013",
    ammount: 1935.13,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 23575,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "Saint Pierre and Miquelon",
    customer: "Eugine",
    service: "Other",
    bank: "ZABA",
    documentDate: "07.08.2018",
    ammount: 7196.94,
    currency: "USD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 75468,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Chile",
    customer: "Adelle",
    service: "Viber",
    bank: "Revolut",
    documentDate: "11.13.2016",
    ammount: 8522.62,
    currency: "USD",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 97975,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Poland",
    customer: "Ebonee",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "11.12.2018",
    ammount: 10000.7,
    currency: "SEK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 96943,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "United Kingdom",
    customer: "Gale",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "01.09.2014",
    ammount: 4212.91,
    currency: "AUD",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 33991,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Japan",
    customer: "Lolita",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "11.27.2013",
    ammount: 3330.03,
    currency: "EUR",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 66904,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Czech Republic",
    customer: "Laure",
    service: "Other",
    bank: "PBZ",
    documentDate: "02.29.2016",
    ammount: 2843.6,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 86668,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "Belize",
    customer: "Catrina",
    service: "Voice",
    bank: "Revolut",
    documentDate: "01.06.2013",
    ammount: 5015.24,
    currency: "SEK",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 23384,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Åland Islands",
    customer: "Keelia",
    service: "WhatsApp",
    bank: "PBZ",
    documentDate: "04.20.2018",
    ammount: 1632.78,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 25776,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Turkmenistan",
    customer: "Karolina",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "08.01.2011",
    ammount: 2678.67,
    currency: "CAD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 77741,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Bhutan",
    customer: "Di",
    service: "SMS",
    bank: "HPB",
    documentDate: "03.22.2013",
    ammount: 5644.91,
    currency: "USD",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 69595,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Malawi",
    customer: "Stephanie",
    service: "Viber",
    bank: "Revolut",
    documentDate: "08.06.2010",
    ammount: 4673.31,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 91191,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "United States",
    customer: "Gisela",
    service: "Other",
    bank: "Revolut",
    documentDate: "10.15.2015",
    ammount: 2509.9,
    currency: "AUD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 67630,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Micronesia, Federated States of",
    customer: "Therine",
    service: "Viber",
    bank: "Hypo",
    documentDate: "07.30.2017",
    ammount: 671.69,
    currency: "AUD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 53288,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Oman",
    customer: "Annaliese",
    service: "Viber",
    bank: "PBZ",
    documentDate: "04.02.2017",
    ammount: 4078.07,
    currency: "AUD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 24520,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Hong Kong",
    customer: "Heida",
    service: "Voice",
    bank: "Hypo",
    documentDate: "03.10.2011",
    ammount: 7834.43,
    currency: "HRK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 55901,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Guam",
    customer: "Charmaine",
    service: "SMS",
    bank: "Revolut",
    documentDate: "11.18.2016",
    ammount: 360.41,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 31578,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Montserrat",
    customer: "Elyssa",
    service: "SMS",
    bank: "Erste",
    documentDate: "10.05.2017",
    ammount: 1500.76,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 31425,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Jordan",
    customer: "Robinia",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "05.19.2012",
    ammount: 6687.55,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 77990,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Liberia",
    customer: "Marleah",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "02.12.2015",
    ammount: 2873.2,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 99119,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Brazil",
    customer: "Claudina",
    service: "WhatsApp",
    bank: "Barclays",
    documentDate: "08.20.2017",
    ammount: 4872.95,
    currency: "EUR",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 73475,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Chile",
    customer: "Tilly",
    service: "SMS",
    bank: "Raiffeisen",
    documentDate: "06.13.2013",
    ammount: 9797.84,
    currency: "SEK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 99942,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "American Samoa",
    customer: "Agnese",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "08.18.2016",
    ammount: 2466.65,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 99254,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Mayotte",
    customer: "Giustina",
    service: "Voice",
    bank: "HPB",
    documentDate: "08.05.2018",
    ammount: 5812.65,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 64214,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Zimbabwe",
    customer: "Harmonia",
    service: "Viber",
    bank: "Erste",
    documentDate: "04.18.2017",
    ammount: 9511.54,
    currency: "USD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 83470,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "Gambia",
    customer: "Jerry",
    service: "WhatsApp",
    bank: "Raiffeisen",
    documentDate: "11.01.2015",
    ammount: 7129.41,
    currency: "HRK",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 91002,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Macao",
    customer: "Elyssa",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "03.20.2018",
    ammount: 5769.1,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 74617,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Comoros",
    customer: "Imojean",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "08.14.2018",
    ammount: 8631.78,
    currency: "USD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 56215,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Qatar",
    customer: "Margalo",
    service: "Viber",
    bank: "OTP",
    documentDate: "01.09.2013",
    ammount: 8474.21,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 43197,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Liberia",
    customer: "Cristabel",
    service: "Voice",
    bank: "Barclays",
    documentDate: "07.29.2011",
    ammount: 4891.62,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 66741,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Madagascar",
    customer: "Jacquetta",
    service: "SMS",
    bank: "Hypo",
    documentDate: "07.11.2018",
    ammount: 857.5,
    currency: "AUD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 34861,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Holy See (Vatican City State)",
    customer: "Hannis",
    service: "Other",
    bank: "OTP",
    documentDate: "07.03.2012",
    ammount: 4171.11,
    currency: "GBP",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 15147,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Macao",
    customer: "Diena",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "12.09.2012",
    ammount: 6496.24,
    currency: "AUD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 15642,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "Eritrea",
    customer: "Dode",
    service: "Voice",
    bank: "Barclays",
    documentDate: "04.03.2014",
    ammount: 2161.78,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 61115,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2016,
    company: "Mauritius",
    customer: "Bettine",
    service: "SMS",
    bank: "Erste",
    documentDate: "06.16.2013",
    ammount: 232.86,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 45933,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Mali",
    customer: "Brooks",
    service: "Other",
    bank: "HPB",
    documentDate: "11.11.2017",
    ammount: 9180.57,
    currency: "SEK",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 22897,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Belize",
    customer: "Etta",
    service: "SMS",
    bank: "Hypo",
    documentDate: "07.26.2018",
    ammount: 6127.23,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 98807,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Israel",
    customer: "Teriann",
    service: "Voice",
    bank: "Raiffeisen",
    documentDate: "01.19.2016",
    ammount: 5416.49,
    currency: "SEK",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 18883,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2013,
    company: "Albania",
    customer: "Elise",
    service: "SMS",
    bank: "HPB",
    documentDate: "08.26.2011",
    ammount: 2928.9,
    currency: "EUR",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 18946,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Belarus",
    customer: "Ilse",
    service: "WhatsApp",
    bank: "OTP",
    documentDate: "05.26.2017",
    ammount: 7735.61,
    currency: "EUR",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 76289,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Finland",
    customer: "Joeann",
    service: "Viber",
    bank: "Barclays",
    documentDate: "03.15.2013",
    ammount: 6588.83,
    currency: "EUR",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 96039,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Liechtenstein",
    customer: "Elora",
    service: "Voice",
    bank: "PBZ",
    documentDate: "10.19.2011",
    ammount: 1855.1,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 61365,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Liechtenstein",
    customer: "Penelopa",
    service: "Viber",
    bank: "Hypo",
    documentDate: "09.21.2017",
    ammount: 1218.11,
    currency: "GBP",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 47772,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Norway",
    customer: "Christal",
    service: "WhatsApp",
    bank: "Erste",
    documentDate: "07.02.2011",
    ammount: 305.38,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 60307,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Italy",
    customer: "Kayla",
    service: "Other",
    bank: "PBZ",
    documentDate: "10.18.2014",
    ammount: 6133.78,
    currency: "GBP",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 49625,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Colombia",
    customer: "Kristina",
    service: "SMS",
    bank: "PBZ",
    documentDate: "10.10.2017",
    ammount: 6961.63,
    currency: "AUD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 24388,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Netherlands Antilles",
    customer: "Correy",
    service: "Voice",
    bank: "Erste",
    documentDate: "07.22.2012",
    ammount: 3953.59,
    currency: "GBP",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 96879,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Northern Mariana Islands",
    customer: "Jemie",
    service: "WhatsApp",
    bank: "Raiffeisen",
    documentDate: "10.09.2010",
    ammount: 2844.46,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 59591,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Holy See (Vatican City State)",
    customer: "Jaclyn",
    service: "Voice",
    bank: "Erste",
    documentDate: "07.02.2015",
    ammount: 7101.55,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 33820,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Dominica",
    customer: "Neila",
    service: "WhatsApp",
    bank: "PBZ",
    documentDate: "07.22.2016",
    ammount: 4219.98,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 86624,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "United States",
    customer: "Rivalee",
    service: "Viber",
    bank: "Hypo",
    documentDate: "01.03.2010",
    ammount: 9588.36,
    currency: "GBP",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 49578,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2019,
    company: "Dominica",
    customer: "Aimil",
    service: "Voice",
    bank: "Revolut",
    documentDate: "01.21.2016",
    ammount: 8701.45,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 89245,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2014,
    company: "Azerbaijan",
    customer: "Jacquetta",
    service: "Voice",
    bank: "Revolut",
    documentDate: "12.24.2010",
    ammount: 282.49,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 93004,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Macedonia, The Former Yugoslav Republic of",
    customer: "Sophia",
    service: "Viber",
    bank: "Barclays",
    documentDate: "09.20.2012",
    ammount: 2378.3,
    currency: "USD",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 20718,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Norfolk Island",
    customer: "Briney",
    service: "SMS",
    bank: "Barclays",
    documentDate: "04.23.2010",
    ammount: 2445.45,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 64389,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2018,
    company: "Japan",
    customer: "Kore",
    service: "Voice",
    bank: "OTP",
    documentDate: "02.21.2011",
    ammount: 5318.47,
    currency: "USD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 63450,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "Samoa",
    customer: "Shel",
    service: "Voice",
    bank: "Barclays",
    documentDate: "08.25.2015",
    ammount: 8764.6,
    currency: "HRK",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 96312,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Fiji",
    customer: "Marleah",
    service: "Voice",
    bank: "ZABA",
    documentDate: "01.17.2016",
    ammount: 7927.33,
    currency: "CAD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 66340,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Vanuatu",
    customer: "Talya",
    service: "Viber",
    bank: "Revolut",
    documentDate: "11.02.2016",
    ammount: 854.3,
    currency: "EUR",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 45240,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Estonia",
    customer: "Fredericka",
    service: "Voice",
    bank: "Hypo",
    documentDate: "06.17.2016",
    ammount: 6822.46,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 78040,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Canada",
    customer: "Marline",
    service: "SMS",
    bank: "ZABA",
    documentDate: "03.01.2013",
    ammount: 6873.82,
    currency: "EUR",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 30197,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Wallis and Futuna",
    customer: "Rebeca",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "07.13.2014",
    ammount: 4769.42,
    currency: "EUR",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 13244,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Western Sahara",
    customer: "Celisse",
    service: "Other",
    bank: "ZABA",
    documentDate: "05.27.2016",
    ammount: 9467.58,
    currency: "SEK",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 11732,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2013,
    company: "Canada",
    customer: "Cindelyn",
    service: "Viber",
    bank: "ZABA",
    documentDate: "08.11.2017",
    ammount: 3337.59,
    currency: "SEK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 88683,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2013,
    company: "Papua New Guinea",
    customer: "Priscilla",
    service: "SMS",
    bank: "Erste",
    documentDate: "09.17.2012",
    ammount: 7364.26,
    currency: "HRK",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 96563,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Bosnia and Herzegovina",
    customer: "Cristabel",
    service: "Voice",
    bank: "Erste",
    documentDate: "12.06.2017",
    ammount: 2977.83,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 30201,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Guinea-Bissau",
    customer: "Dorothy",
    service: "WhatsApp",
    bank: "ZABA",
    documentDate: "10.14.2018",
    ammount: 1452.15,
    currency: "EUR",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 95225,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "New Zealand",
    customer: "Gui",
    service: "Viber",
    bank: "Erste",
    documentDate: "04.20.2015",
    ammount: 6984.5,
    currency: "GBP",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 56531,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2011,
    company: "Mauritius",
    customer: "Elfreda",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "09.09.2016",
    ammount: 3658.84,
    currency: "CAD",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 84027,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Seychelles",
    customer: "Luci",
    service: "SMS",
    bank: "ZABA",
    documentDate: "11.06.2010",
    ammount: 1447.41,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 10883,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Kazakhstan",
    customer: "Dania",
    service: "WhatsApp",
    bank: "PBZ",
    documentDate: "02.12.2014",
    ammount: 7001.47,
    currency: "HRK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 86949,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "United States",
    customer: "Halette",
    service: "Voice",
    bank: "Barclays",
    documentDate: "01.13.2016",
    ammount: 4108.31,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 77981,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Nicaragua",
    customer: "Roslyn",
    service: "SMS",
    bank: "Revolut",
    documentDate: "12.01.2014",
    ammount: 994.83,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 18908,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2015,
    company: "Equatorial Guinea",
    customer: "Brynna",
    service: "SMS",
    bank: "ZABA",
    documentDate: "06.12.2017",
    ammount: 5552.55,
    currency: "GBP",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 23215,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Viet Nam",
    customer: "Amii",
    service: "Voice",
    bank: "OTP",
    documentDate: "05.30.2013",
    ammount: 4750.26,
    currency: "SEK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 74152,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2017,
    company: "Nigeria",
    customer: "Blondelle",
    service: "WhatsApp",
    bank: "Raiffeisen",
    documentDate: "11.16.2016",
    ammount: 7828,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 27583,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Senegal",
    customer: "Ofilia",
    service: "SMS",
    bank: "Raiffeisen",
    documentDate: "01.08.2016",
    ammount: 1873.47,
    currency: "EUR",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 39005,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2013,
    company: "Guinea-Bissau",
    customer: "Gavrielle",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "05.15.2016",
    ammount: 7387.88,
    currency: "USD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 32912,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2018,
    company: "Tajikistan",
    customer: "Brandise",
    service: "WhatsApp",
    bank: "HPB",
    documentDate: "12.14.2014",
    ammount: 5725.03,
    currency: "SEK",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 85790,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Cocos (Keeling) Islands",
    customer: "Mireielle",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "10.24.2013",
    ammount: 2043.4,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 78675,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "Montserrat",
    customer: "Feliza",
    service: "Viber",
    bank: "Barclays",
    documentDate: "09.13.2015",
    ammount: 8002.62,
    currency: "GBP",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 92096,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2016,
    company: "United Kingdom",
    customer: "Kaja",
    service: "Other",
    bank: "Erste",
    documentDate: "08.21.2014",
    ammount: 6742.78,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 98063,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "Estonia",
    customer: "Priscilla",
    service: "SMS",
    bank: "Hypo",
    documentDate: "12.27.2012",
    ammount: 2164.64,
    currency: "EUR",
    dueIn: "Today",
    isPaid: true
  },
  {
    documentNumber: 49208,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2014,
    company: "Namibia",
    customer: "Elyssa",
    service: "Viber",
    bank: "Erste",
    documentDate: "02.12.2017",
    ammount: 3013.85,
    currency: "USD",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 50982,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Dominican Republic",
    customer: "Agnese",
    service: "SMS",
    bank: "Barclays",
    documentDate: "12.19.2012",
    ammount: 8684.89,
    currency: "USD",
    dueIn: "60-90",
    isPaid: true
  },
  {
    documentNumber: 75711,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "El Salvador",
    customer: "Genevra",
    service: "Voice",
    bank: "Revolut",
    documentDate: "01.07.2017",
    ammount: 4274.06,
    currency: "GBP",
    dueIn: "30-60",
    isPaid: true
  },
  {
    documentNumber: 97029,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2016,
    company: "Taiwan, Province of China",
    customer: "Jackie",
    service: "Voice",
    bank: "Hypo",
    documentDate: "07.06.2014",
    ammount: 9145.56,
    currency: "SEK",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 47889,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2019,
    company: "Canada",
    customer: "Shaylyn",
    service: "Viber",
    bank: "PBZ",
    documentDate: "07.27.2012",
    ammount: 9900.01,
    currency: "CAD",
    dueIn: "60-90",
    isPaid: false
  },
  {
    documentNumber: 45211,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2010,
    company: "Denmark",
    customer: "Janeczka",
    service: "Viber",
    bank: "OTP",
    documentDate: "05.21.2011",
    ammount: 5991.65,
    currency: "GBP",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 94237,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2015,
    company: "Korea, Republic of",
    customer: "Donetta",
    service: "Viber",
    bank: "Erste",
    documentDate: "10.11.2014",
    ammount: 5997.77,
    currency: "GBP",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 30814,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2014,
    company: "Falkland Islands (Malvinas)",
    customer: "Joceline",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "02.12.2015",
    ammount: 3620.02,
    currency: "AUD",
    dueIn: "15-30",
    isPaid: true
  },
  {
    documentNumber: 53765,
    documentType: "Proforma Invoice",
    documentStatus: "In process",
    fiscalYear: 2011,
    company: "Serbia and Montenegro",
    customer: "Almeta",
    service: "Viber",
    bank: "Hypo",
    documentDate: "07.30.2015",
    ammount: 3371.08,
    currency: "AUD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 61385,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Panama",
    customer: "Rosaline",
    service: "WhatsApp",
    bank: "Hypo",
    documentDate: "12.26.2017",
    ammount: 8766.01,
    currency: "CAD",
    dueIn: "15-30",
    isPaid: false
  },
  {
    documentNumber: 27012,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2017,
    company: "American Samoa",
    customer: "Nananne",
    service: "Other",
    bank: "Raiffeisen",
    documentDate: "11.13.2015",
    ammount: 7328.49,
    currency: "EUR",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 87801,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2010,
    company: "Guatemala",
    customer: "Gloria",
    service: "Other",
    bank: "OTP",
    documentDate: "01.10.2017",
    ammount: 8173.68,
    currency: "SEK",
    dueIn: "Today",
    isPaid: false
  },
  {
    documentNumber: 26191,
    documentType: "Invoice",
    documentStatus: "Done",
    fiscalYear: 2019,
    company: "Saint Lucia",
    customer: "Vere",
    service: "Other",
    bank: "Revolut",
    documentDate: "06.05.2011",
    ammount: 351.4,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: true
  },
  {
    documentNumber: 92846,
    documentType: "Proforma Invoice",
    documentStatus: "Done",
    fiscalYear: 2012,
    company: "Guyana",
    customer: "Margalo",
    service: "Viber",
    bank: "PBZ",
    documentDate: "11.25.2010",
    ammount: 3040.62,
    currency: "USD",
    dueIn: "over 120",
    isPaid: true
  },
  {
    documentNumber: 86939,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "French Polynesia",
    customer: "Carlie",
    service: "SMS",
    bank: "Erste",
    documentDate: "03.24.2018",
    ammount: 872.52,
    currency: "CAD",
    dueIn: "90-120",
    isPaid: false
  },
  {
    documentNumber: 25675,
    documentType: "Invoice",
    documentStatus: "On hold",
    fiscalYear: 2012,
    company: "Comoros",
    customer: "Maisey",
    service: "Voice",
    bank: "Revolut",
    documentDate: "03.31.2011",
    ammount: 7385.88,
    currency: "EUR",
    dueIn: "30-60",
    isPaid: false
  },
  {
    documentNumber: 51897,
    documentType: "Invoice",
    documentStatus: "In process",
    fiscalYear: 2018,
    company: "French Southern Territories",
    customer: "Kaia",
    service: "Viber",
    bank: "PBZ",
    documentDate: "12.20.2012",
    ammount: 6912.34,
    currency: "GBP",
    dueIn: "over 120",
    isPaid: false
  },
  {
    documentNumber: 59062,
    documentType: "Proforma Invoice",
    documentStatus: "On hold",
    fiscalYear: 2011,
    company: "Angola",
    customer: "Helena",
    service: "WhatsApp",
    bank: "Revolut",
    documentDate: "05.20.2014",
    ammount: 7516.43,
    currency: "HRK",
    dueIn: "15-30",
    isPaid: true
  }
];
